name: scrubby
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools>=1.20
  - bowtie2>=2.5.4
  - minimap2>=2.28
  - strobealign=0.13.0
  - kraken2>=2.1.3
  - metabuli>=1.0.5
  - minigraph=0.21
  # - pytorch::pytorch=2.3.0  # LIBTORCH_USE_PYTORCH=1 to use 'libtorch' through a PyTorch installation for '--features nn' builds 